# Generated by Django 3.0.5 on 2020-04-15 19:12

import core.util
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('date_modificado', models.DateTimeField(auto_now=True, null=True)),
                ('descricao', models.CharField(max_length=255)),
                ('url_original', models.CharField(max_length=255)),
                ('url_encurtado', models.CharField(default=core.util.encurtar_link, editable=False, max_length=20, unique=True)),
                ('contador', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
